// WARNING: Please don't edit this file. It was generated by C++/WinRT v3.0.260818.1

void* winrt_make_LocalGit_MainWindow()
{
    return winrt::detach_abi(winrt::make<winrt::LocalGit::factory_implementation::MainWindow>());
}
WINRT_EXPORT namespace winrt::LocalGit
{
    MainWindow::MainWindow() :
        MainWindow(make<LocalGit::implementation::MainWindow>())
    {
    }
}
